<html>
<head>
<META http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>entmake</title>
<link type="text/css" href="ac.acad_ak.css" rel="StyleSheet">
<link media="print" type="text/css" href="ac.acad_ak_print.css" rel="StyleSheet">
<script src="ac_common.js" language="javascript"></script><script src="ac.strings.js" language="javascript"></script><script src="ac.acad_ak.js" language="javascript"></script>
</head>
<body bgcolor="#ffffff">
<div class="HeadingDiv">
<table class="HeadingTable" border="0" cellspacing="0" cellpadding="0" width="103%">
<tr valign="top">
<td class="BookTitleCell" height="29">
<div class="BookTitle">
<a href="ALR.default.001.htm"><span class="BookTitleLink">明经通道 AutoLISP 函数</span></a>
</div>	
									&nbsp;
								</td><td align="right">
<table border="0" cellspacing="0" cellpadding="0" class="HeadNavTable">
<tr>
<td class="InfoLine" id="infoline" align="right">明经通道 AutoLISP 函数&nbsp;</td><td class="NavGif"><a title="回到上一层..." href="ALR.default.001.htm"><span onmouseout="showinfo(0);" onmouseover="showinfo(1);" class="HeadNavLink"><img border="0" src="ac.pg_up.gif"></span></a></td><td>&nbsp;</td>  
</tr>
</table>
</td>
</tr>
<tr>
<td colspan="2">
<div class="TopHead">entmake</div>
</td>
</tr>
<tr valign="bottom">
<td height="33" colspan="2">
<table cellpadding="0" cellspacing="0" border="0" class="TabTable">
<tr>
<td width="10">&nbsp;</td>
</tr>
</table>
</td>
</tr>
</table>
</div>
<p id="crleadin" class="cr_leadin">在图形中创建一个新图元</p>
<pre class="prog_in_end">(entmake [elist])</pre>
<p class="body">entmake 函数能够定义图形或非图形对象。</p>  
<p class="Heading-2">参数</p>
<p class="define_head">elist</p>
<p class="define_text">图元定义数据表，其格式与 entget 函数所返回表的格式相似。elist 参数必须包含创建图元的全部必要数据。如果省略了任何一个必须的定义数据，该函数就会返回 nil 并拒绝创建该图元。如果省略了可选的定义数据（如图层），entmake 使用缺省值。</p>  
<p class="define_text">图元类型（如 CIRCLE 或 LINE）必须是 elist 参数所指的表中的第一项或第二项。如果是第二项，那么第一项必须是图元名。在这种情况下，entmake 函数创建新图元时会忽略图元名。如果 elist 参数中包含了图元句柄，该句柄也会被忽略。</p>  
<p class="Heading-2">返回值</p>
<p class="body">如果成功，则 entmake 返回定义数据的图元表。如果 entmake 无法创建图元，则返回 nil。</p>  
<p class="body">块定义完成后（对 endblk 使用 entmake）返回块名，而不是通常返回的图元表。关于定义块的详细信息，请参见  
《Visual LISP 开发人员手册》中的创建复杂图元。</p> 
<p class="Heading-2">示例</p>
<p class="body">下面的代码创建一个红色的圆 (color 62)，圆心为 (4,4)，半径为 1。可选的图层和线型选项都被省略了，因此假设其为缺省值。</p>  
<p class="prompt_end">命令： <span class="CharSansBold">(entmake '((0 . "CIRCLE") 
(62 . 1) (10 4.0 4.0 0.0) (40 . 1.0)))</span> 
</p>
<p class="prompt_end">((0 . "CIRCLE") (62
. 1) (10 4.0 4.0 0.0) (40 . 1.0))</p>
<p class="body"> 使用说明</p>
<p class="body">不能使用 entmake 创建视口对象。</p>  
<p class="body">只有插入图元才承认 66 组码，表示属性跟随。多段线的 66 组码被强制性地置为 1 以表示顶点跟随，其他图元该组码的缺省值为 0。紧随多段线图元后的只能是顶点图元。</p>  
<p class="body">调用 entmake 函数时，尺寸图元的组码 2（块名部分）是可选的。如果在图元定义数据表中省略了块名，AutoCAD 将创建一个新块；否则它用提供的块名创建尺寸。</p>  
<p class="body">由于历史原因，<span class="CharCourierBold">entmake</span> 
忽略以下图元类型的 DXF 组码 100：</p> 
<ul>
<li class="list_bulleted_begin">AcDbText</li>
<li class="list_bulleted">AcDbAttribute</li>
<li class="list_bulleted">AcDbAttributeDefinition</li>
<li class="list_bulleted">AcDbBlockBegin</li>
<li class="list_bulleted">AcDbBlockEnd</li>
<li class="list_bulleted">AcDbSequenceEnd</li>
<li class="list_bulleted">AcDbBlockReference</li>
<li class="list_bulleted">AcDbMInsertBlock</li>
<li class="list_bulleted">AcDb2dVertex</li>
<li class="list_bulleted">AcDb3dPolylineVertex</li>
<li class="list_bulleted">AcDbPolygonMeshVertex</li>
<li class="list_bulleted">AcDbPolyFaceMeshVertex</li>
<li class="list_bulleted">AcDbFaceRecord</li>
<li class="list_bulleted">AcDb2dPolyline</li>
<li class="list_bulleted">AcDb3dPolyline</li>
<li class="list_bulleted">AcDbArc</li>
<li class="list_bulleted">AcDbCircle</li>
<li class="list_bulleted">AcDbLine</li>
<li class="list_bulleted">AcDbPoint</li>
<li class="list_bulleted">AcDbFace</li>
<li class="list_bulleted">AcDbPolyFaceMesh</li>
<li class="list_bulleted">AcDbPolygonMesh</li>
<li class="list_bulleted">AcDbTrace</li>
<li class="list_bulleted">AcDbSolid</li>
<li class="list_bulleted">AcDbShape</li>
<li class="list_bulleted_end">AcDbViewport</li>
</ul>
<p class="see_also">参阅</p>
<p class="body"> <a href="ALR.default.085.htm">entdel</a>、 <a href="ALR.default.086.htm">entget</a>、 <a href="ALR.default.090.htm">entmod</a>  
和 <a href="ALR.default.135.htm">handent</a>  
函数。《AutoLISP开发人员手册》中的 <a href="ms-its:ACAD_ALG.chm::/ALG.10.015.htm">图元数据函数</a>  
介绍在图形中创建图元的其他信息， <a href="ms-its:ACAD_ALG.chm::/ALG.10.019.htm">向图形中添加图元</a>专门介绍 entmake 的使用， <a href="ms-its:ACAD_ALG.chm::/ALG.10.020.htm">创建复杂图元</a>介绍创建复杂图元的信息。 </p>  
<table cellpadding="4" cellspacing="0" border="0" width="100%" class="FooterTable">
<tr valign="top">
<td><P class=element><a href=http://www.mjtd.com>明经通道</a> 版权所有 未经许可 不得传播</td><td><script language=javascript src='ac.acad_mc.js'></script></td><td align="right">&nbsp;<a href="javascript:doComments();"><span class="CommentsLink" title="点击此处发送有关对本主题的评论">评论</span></a>&nbsp;</td>
</tr>
</table>
<p class="footer_padding">&nbsp;</p>
</body> 
</html>
